import string

MAX_LENGTH_NAME_RECIPE = 256
MAX_LENGTH_TAG = 32
MAX_LENGTH_NAME_INGREDIENT = 128
MAX_LENGTH_MEASUREMENT_UNIT = 64
MAX_LENGTH_TEXT_RECIPE = 1256
MIN_AMOUNT_INGREDIENT = 1
MAX_AMOUNT_INGREDIENT = 666666
MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 1440
STRING_FOR_RANDOM = string.ascii_letters + string.digits
MAX_LENGTH_SHORT_LINK = 3
