version: '3.3'

volumes:
  postgres_data:
  backend_static:
  backend_media:
  frontend_static:

networks:
  foodgram-network:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
    networks:
        - foodgram-network

  backend:
    image: by9n/foodgram_backend:latest
    restart: always
    volumes:
        - backend_static:/app/static
        - backend_media:/app/media
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
        - foodgram-network

  frontend:
    image: by9n/foodgram_frontend:latest
    depends_on:
        - db
        - backend
    volumes:
        - frontend_static:/app/result_build/build
    networks:
        - foodgram-network

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "9090:80"
    volumes:
        - ./nginx.production.conf:/etc/nginx/conf.d/default.conf
        - frontend_static:/usr/share/nginx/html/
        - ../docs/:/usr/share/nginx/html/api/docs/
        - backend_static:/backend_static
        - backend_media:/backend_media
    depends_on:
        - backend
        - frontend
    restart: always
    networks:
        - foodgram-network