# Generated by Django 3.2.3 on 2024-07-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_favoriterecipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
