# Generated by Django 3.2.16 on 2024-04-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20240402_1046'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_name_recipe',
        ),
    ]
