# Generated by Django 3.2.3 on 2024-08-05 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20240805_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='amount',
            field=models.PositiveSmallIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество 1!')], verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
