# Generated by Django 3.2.3 on 2024-08-21 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20240814_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Нельзя приготовить быстрее чем за 1'), django.core.validators.MaxValueValidator(32000, 'Время приготовления не может быть выше 32000')], verbose_name='Время приготовления в минутах.'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество 1!'), django.core.validators.MaxValueValidator(32000, message='Максимальное количество 32000!')], verbose_name='Количество'),
        ),
    ]
